const mongoose = require('mongoose');

// ─── Schedule ─────────────────────────────────────────────────────────────────
const scheduleSchema = new mongoose.Schema({
  bus: { type: mongoose.Schema.Types.ObjectId, ref: 'Bus', required: true },
  driver: { type: mongoose.Schema.Types.ObjectId, ref: 'Driver', required: true },
  route: { type: mongoose.Schema.Types.ObjectId, ref: 'Route', required: true },
  date: { type: Date, required: true },
  departureTime: { type: String, required: true },
  estimatedArrival: { type: String, required: true },
  actualDeparture: { type: String, default: null },
  actualArrival: { type: String, default: null },
  status: {
    type: String,
    enum: ['scheduled', 'running', 'completed', 'cancelled', 'delayed'],
    default: 'scheduled'
  },
  delayMinutes: { type: Number, default: 0 },
  currentStopIndex: { type: Number, default: 0 },
  autoGenerated: { type: Boolean, default: true },
  notes: { type: String, default: '' }
}, { timestamps: true });

// ─── Incident ─────────────────────────────────────────────────────────────────
const incidentSchema = new mongoose.Schema({
  bus: { type: mongoose.Schema.Types.ObjectId, ref: 'Bus', required: true },
  driver: { type: mongoose.Schema.Types.ObjectId, ref: 'Driver' },
  route: { type: mongoose.Schema.Types.ObjectId, ref: 'Route' },
  type: {
    type: String,
    enum: ['breakdown', 'accident', 'traffic', 'road-closure', 'passenger-issue', 'other'],
    required: true
  },
  severity: { type: String, enum: ['low', 'medium', 'high', 'critical'], default: 'medium' },
  description: { type: String, required: true },
  location: {
    lat: { type: Number },
    lng: { type: Number },
    address: { type: String }
  },
  status: { type: String, enum: ['open', 'in-progress', 'resolved'], default: 'open' },
  reportedAt: { type: Date, default: Date.now },
  resolvedAt: { type: Date, default: null },
  replacementBus: { type: mongoose.Schema.Types.ObjectId, ref: 'Bus', default: null },
  affectedStops: [{ type: String }],
  resolutionNotes: { type: String, default: '' }
}, { timestamps: true });

// ─── Depot ────────────────────────────────────────────────────────────────────
const depotSchema = new mongoose.Schema({
  depotId: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  location: { type: String, required: true },
  lat: { type: Number, required: true },
  lng: { type: Number, required: true },
  capacity: { type: Number, default: 80 },
  incharge: { type: String, default: '' },
  phone: { type: String, default: '' }
}, { timestamps: true });

// ─── User (Admin/Operator) ────────────────────────────────────────────────────
const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true, lowercase: true },
  password: { type: String, required: true },
  role: { type: String, enum: ['admin', 'operator', 'viewer'], default: 'operator' },
  depot: { type: mongoose.Schema.Types.ObjectId, ref: 'Depot', default: null },
  active: { type: Boolean, default: true }
}, { timestamps: true });

module.exports = {
  Schedule: mongoose.model('Schedule', scheduleSchema),
  Incident: mongoose.model('Incident', incidentSchema),
  Depot: mongoose.model('Depot', depotSchema),
  User: mongoose.model('User', userSchema)
};
