/**
 * DTC Scheduling Engine
 * Algorithm: Greedy + Constraint Satisfaction
 *
 * Steps:
 * 1. Load all active routes sorted by priority (desc)
 * 2. For each route, find an available bus at the route's depot
 * 3. Check bus constraints (not in maintenance, not already assigned)
 * 4. Find an available driver at the same depot
 * 5. Check driver constraints (shift hours, license valid)
 * 6. Assign and mark both as occupied
 * 7. Calculate departure times based on route frequency
 */

const Bus = require('../models/Bus');
const Driver = require('../models/Driver');
const Route = require('../models/Route');
const { Schedule } = require('../models/index');

async function generateSchedule(targetDate = new Date()) {
  // Normalize to start of day
  const date = new Date(targetDate);
  date.setHours(0, 0, 0, 0);

  console.log(`\n🔄 Generating schedule for ${date.toDateString()}...`);

  // Step 1: Load all active routes sorted by priority desc
  const routes = await Route.find({ status: 'active' }).sort({ priority: -1 });

  // Step 2: Load available buses per depot
  const buses = await Bus.find({ status: { $in: ['idle', 'active'] } });
  const availableBuses = new Map(); // depotId -> [bus, ...]
  buses.forEach(bus => {
    const key = bus.depot.toString();
    if (!availableBuses.has(key)) availableBuses.set(key, []);
    availableBuses.get(key).push({ bus, assigned: false });
  });

  // Step 3: Load available drivers per depot
  const drivers = await Driver.find({ status: { $in: ['available'] } });
  const availableDrivers = new Map(); // depotId -> [driver, ...]
  drivers.forEach(driver => {
    const key = driver.depot.toString();
    if (!availableDrivers.has(key)) availableDrivers.set(key, []);
    availableDrivers.get(key).push({ driver, assigned: false });
  });

  const assignments = [];
  const conflicts = [];

  // Step 4: Greedy assignment loop
  for (const route of routes) {
    const depotKey = route.depot.toString();

    // Calculate how many trips needed for this route today
    const startMin = timeToMinutes(route.operatingHours.start);
    const endMin = timeToMinutes(route.operatingHours.end);
    const tripsNeeded = Math.floor((endMin - startMin) / route.frequency);

    const depotBuses = availableBuses.get(depotKey) || [];
    const depotDrivers = availableDrivers.get(depotKey) || [];

    // Assign buses for each departure slot
    let currentTime = startMin;
    let tripsAssigned = 0;

    for (let t = 0; t < Math.min(tripsNeeded, 3); t++) { // cap at 3 trips per route in MVP
      const busSlot = depotBuses.find(b => !b.assigned && !b.bus.needsMaintenance);
      const driverSlot = depotDrivers.find(d => !d.assigned && isDriverAvailable(d.driver, currentTime));

      if (!busSlot || !driverSlot) {
        conflicts.push({
          route: route.routeNo,
          reason: !busSlot ? 'No available bus' : 'No available driver',
          time: minutesToTime(currentTime)
        });
        currentTime += route.frequency;
        continue;
      }

      // Mark as assigned
      busSlot.assigned = true;
      driverSlot.assigned = true;

      const departureTime = minutesToTime(currentTime);
      const arrivalTime = minutesToTime(currentTime + route.avgDuration);

      assignments.push({
        bus: busSlot.bus._id,
        driver: driverSlot.driver._id,
        route: route._id,
        date,
        departureTime,
        estimatedArrival: arrivalTime,
        status: 'scheduled',
        autoGenerated: true
      });

      tripsAssigned++;
      currentTime += route.frequency;

      // Free bus after trip completes (greedy re-use)
      const busReleaseTime = currentTime + route.avgDuration + 30; // 30 min buffer
      setTimeout(() => { busSlot.assigned = false; }, 10); // in real impl, use time-based queue
    }
  }

  // Step 5: Delete today's existing auto-generated schedule and insert new
  await Schedule.deleteMany({ date, autoGenerated: true });
  const created = await Schedule.insertMany(assignments);

  // Step 6: Update bus statuses
  await Bus.updateMany(
    { _id: { $in: assignments.map(a => a.bus) } },
    { status: 'dispatched' }
  );

  // Step 7: Update driver statuses
  await Driver.updateMany(
    { _id: { $in: assignments.map(a => a.driver) } },
    { status: 'on-duty' }
  );

  const result = {
    date: date.toDateString(),
    totalRoutes: routes.length,
    assignmentsCreated: created.length,
    conflicts: conflicts.length,
    conflictDetails: conflicts,
    coverage: `${Math.round((created.length / routes.length) * 100)}%`
  };

  console.log(`✅ Schedule generated: ${created.length} assignments, ${conflicts.length} conflicts`);
  return result;
}

// ─── Find replacement bus for incident rerouting ──────────────────────────────
async function findReplacementBus(incidentBusId, depotId) {
  const replacement = await Bus.findOne({
    _id: { $ne: incidentBusId },
    depot: depotId,
    status: 'idle'
  }).populate('depot');

  if (!replacement) {
    // Try any idle bus from any depot
    return await Bus.findOne({
      _id: { $ne: incidentBusId },
      status: 'idle'
    }).populate('depot');
  }
  return replacement;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────
function timeToMinutes(timeStr) {
  const [h, m] = timeStr.split(':').map(Number);
  return h * 60 + m;
}

function minutesToTime(minutes) {
  const h = Math.floor(minutes / 60) % 24;
  const m = minutes % 60;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
}

function isDriverAvailable(driver, currentTimeMinutes) {
  const shiftStart = timeToMinutes(driver.shiftStart);
  const shiftEnd = timeToMinutes(driver.shiftEnd);
  return currentTimeMinutes >= shiftStart &&
         currentTimeMinutes < shiftEnd &&
         driver.hoursWorkedToday < 8 &&
         driver.status === 'available';
}

module.exports = { generateSchedule, findReplacementBus, timeToMinutes, minutesToTime };
